# Generated by Django 3.1.1 on 2021-04-02 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 20, 21, 37, 624261)),
        ),
    ]
